USE [master]
GO

/****** Object:  Database [Student Management]    Script Date: 08/19/2019 05:52:23 ******/
CREATE DATABASE [Student Management] ON  PRIMARY 
( NAME = N'Student Management', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Student Management.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Student Management_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Student Management_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Student Management] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Student Management].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Student Management] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Student Management] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Student Management] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Student Management] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Student Management] SET ARITHABORT OFF 
GO

ALTER DATABASE [Student Management] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Student Management] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Student Management] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Student Management] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Student Management] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Student Management] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Student Management] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Student Management] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Student Management] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Student Management] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Student Management] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Student Management] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Student Management] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Student Management] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Student Management] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Student Management] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Student Management] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Student Management] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Student Management] SET  READ_WRITE 
GO

ALTER DATABASE [Student Management] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Student Management] SET  MULTI_USER 
GO

ALTER DATABASE [Student Management] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Student Management] SET DB_CHAINING OFF 
GO

